export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const CLEAR_SELECTED_USER = 'CLEAR_SELECTED_USER';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_CC_REQUESTS = 'FETCH_CC_REQUESTS';
export const FETCH_LECTURERS = 'FETCH_LECTURERS';